= JUG.CH Sponsorslides
ifdef::env-github[:outfilesuffix: .adoc]

image:https://travis-ci.org/jugch/sponsorslides.svg?branch=master["Build Status", link="https://travis-ci.org/jugch/sponsorslides"]
image:https://img.shields.io/badge/gitmoji-%20😜%20😍-FFDD67.svg["gitmoji", link="https://gitmoji.carloscuesta.me"]

*A small app showing the sponsors on the beamer before each talk at the Java User Group Switzerland.*

== Copyright and Licensing

Copyright (C) 2018 Java User Group Switzerland

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

See the <<LICENSE#,LICENSE>> file for details.
